version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: docker-compose build
      - run:
          name: Run application test
          command: docker-compose run test

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 6" # UTC (am 9:00 JST every Saturday)
          filters:
            branches:
              only:
                - master
    jobs:
      - build
